name: reedmace_dogs
description: Dogs support for reedmace
version: 1.0.0-dev.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  dogs_core: ^9.0.0
  uuid: ^4.3.3
  conduit_open_api: ^4.4.0
  lyell: ^1.1.0
  collection: ^1.18.0
  reedmace_shared: ^1.0.0-dev.4

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
