name: shared
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  dogs_core: ^8.3.0

  reedmace_shared: any
  reedmace_dogs: any

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
  dogs_generator: ^5.3.0

dogs:
  library: true