name: reedmace_client_generator
description: Code generator for the reedmace client library
version: 1.0.0-dev.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build: '>=2.0.0 <3.0.0'
  analyzer: ">=2.0.0 <7.0.0"
  source_gen: '>=1.0.0 <=2.0.0'
  collection: '>=1.15.0 <2.0.0'
  crypto: '>=3.0.0 <4.0.0'
  glob: '>=2.0.0 <3.0.0'
  path: '>=1.8.0 <2.0.0'
  code_builder: '>=4.3.0 <5.0.0'
  dart_style: '>=2.2.4 <3.0.0'

  reedmace: ^1.0.0-dev.4

  build_runner: ^2.4.8
  lyell: ^1.1.0
  lyell_gen: ^1.3.0
  uuid: ^4.3.3

  conduit_open_api: ^4.4.0
  conduit_codable: ^4.4.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
