name: shared
description: Shared library for reedmace application
version: 0.0.1
publish_to: 'none'
environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  reedmace_shared: any
  {{#useDogs}}dogs_core: ^8.4.0
  reedmace_dogs: any
  {{/useDogs}}

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
  {{#useDogs}}dogs_generator: ^5.3.0
  {{/useDogs}}
{{#useDogs}}
dogs:
  library: true
{{/useDogs}}