name: reedmace
description: Easy to use minimalistic web framework for dart
version: 1.0.0-dev.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  shelf_router: ^1.1.4
  shelf: ^1.4.1
  lyell: ^1.1.0
  conduit_open_api: ^4.4.0
  routingkit: ^0.2.1
  canister: ^1.2.2
  recase: ^4.1.0
  collection: ^1.18.0
  glob: ^2.1.2
  reedmace_shared: ^1.0.0-dev.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
