name: reedmace_client
description: A starting point for Dart libraries or applications.
version: 1.0.0-dev.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.4.0
  http: ^1.2.0
  lyell: ^1.1.0
  reedmace_shared: any

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
