name: server
description: Server for reedmace application
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  reedmace: any
  shared:
    path: ../shared
  {{#useDogs}}
  dogs_core: ^8.3.0
  {{/useDogs}}

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
  reedmace_generator: any
  {{#useDogs}}
  dogs_generator: ^5.3.0
  {{/useDogs}}
