name: reedmace_shared
description: Shared library for reedmace application
version: 1.0.0-dev.4
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  lyell: ^1.1.0
  collection: ^1.18.0
  conduit_open_api: ^4.4.0
  conduit_codable: ^4.4.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
