name: smoke
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dogs_core: ^9.0.0
  reedmace: any
  shared:
    path: ../shared
  shelf: ^1.4.1
  conduit_open_api: ^4.4.0
dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
  reedmace_generator: any
